### PR TITLE
adds ftol as option to fit_models

### PR DESCRIPTION
**Pull request by caelanradford**
This adds ftol as an option to fit_models, which will be helpful for looking at different parameters and likelihood types when fitting and comparing global epistasis models.

### CODE REVIEW

**Review by jbloom — CHANGES_REQUESTED** [review]
@caelanradford, don't design this change to pass `ftol` explicitly to `fit_models` and then `fit`. Instead using `**kwargs` to enable passing of arbitrary keyword arguments from `fit_models` to `fit`. 

Sort of like `**kwargs` is used here: https://jbloomlab.github.io/polyclonal/_modules/polyclonal/polyclonal.html#Polyclonal.activity_wt_barplot

Also, looks like tests are failing for various reasons probably related to new package versions and not your pull request. If you want me to fix those first, raise an issue. Otherwise you can try to fix them in your pull request.

**Comment by jbloom** [comment]
@caelanradford, if you still want to make this change, I have fixed the failing tests so you can rebase on top of the current `master` branch and then make changes above.

**Comment by jbloom** [comment]
@caelanradford, I pushed two more commits to this so it passes tests and version is updated. Should I go ahead and merge this or do you have more related changes first?

**Comment by caelanradford** [comment]
You can go ahead and merge. Thanks.

**Pull request merged**
